name: build

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - master

env:
  BUILD_TYPE: Release

jobs:
  macos64:
    name: 'macOS 64-bit'
    runs-on: [macos-latest]
    env:
      MIN_MACOS_VERSION: '10.13'
      MACOS_DEPS_VERSION: '2020-12-22'
      QT_VERSION: '5.15.2'
      SIGN_IDENTITY: ''
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
        with:
          path: obs-text-pthread
      - name: 'checkout OBS-Studio'
        uses: actions/checkout@v2
        with:
          repository: obsproject/obs-studio
          ref: 26.1.2
          path: obs-studio
      - name: 'build OBS Studio'
        run: 'cd obs-studio && ./CI/full-build-macos.sh'
