name: Plugin Build on Docker

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
    tags:
      - '*'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - main

env:
  artifactName: ${{ contains(github.ref_name, '/') && 'docker-artifact' || github.ref_name }}

jobs:
  fedora_setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setup.outputs.matrix }}
    steps:
      - id: setup
        uses: noris-plugins-for-obs/fedora-plugin-devel/setup@main

  fedora_build:
    runs-on: ubuntu-latest
    needs: fedora_setup
    strategy:
      matrix: ${{ fromJSON(needs.fedora_setup.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Check plugin version
        id: version
        run: |
          set -e
          version="$(git describe --tags | sed -e 's/-\([0-9]\+\)-g\([0-9a-f]\+\)$/^\1.git\2/' -e 's/-\(rc[0-9]*\)/~\1/')"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Build plugin
        uses: noris-plugins-for-obs/fedora-plugin-devel@main
        with:
          dists: ${{ matrix.fedora }}
          spec: packaging/fedora/*.spec
          version: ${{ steps.version.outputs.version }}
          rpmbuild_dir: fc-rpmbuild

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.artifactName }}-fedora${{ matrix.fedora }}
          path: |
            fc-rpmbuild/RPMS/*/*.rpm
            fc-rpmbuild/SRPMS/*.rpm
